/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWomenRouteImport } from './routes/_layout/women'
import { Route as LayoutMenRouteImport } from './routes/_layout/men'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWomenRoute = LayoutWomenRouteImport.update({
  id: '/women',
  path: '/women',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMenRoute = LayoutMenRouteImport.update({
  id: '/men',
  path: '/men',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/men': typeof LayoutMenRoute
  '/women': typeof LayoutWomenRoute
}
export interface FileRoutesByTo {
  '/men': typeof LayoutMenRoute
  '/women': typeof LayoutWomenRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/men': typeof LayoutMenRoute
  '/_layout/women': typeof LayoutWomenRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/men' | '/women'
  fileRoutesByTo: FileRoutesByTo
  to: '/men' | '/women' | '/'
  id: '__root__' | '/_layout' | '/_layout/men' | '/_layout/women' | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/women': {
      id: '/_layout/women'
      path: '/women'
      fullPath: '/women'
      preLoaderRoute: typeof LayoutWomenRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/men': {
      id: '/_layout/men'
      path: '/men'
      fullPath: '/men'
      preLoaderRoute: typeof LayoutMenRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutMenRoute: typeof LayoutMenRoute
  LayoutWomenRoute: typeof LayoutWomenRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutMenRoute: LayoutMenRoute,
  LayoutWomenRoute: LayoutWomenRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
